In [1]:
import numpy as np
import pandas as ps

In [6]:
dict = {
    "name":['harry', 'aryan', 'tanish', 'karteek'],
    "marks":[99, 95, 93, 85],
    "country":['US', 'India', 'India', 'UK']
}

In [12]:
df = pd.DataFrame(dict)

In [13]:
df

      name  marks country
0    harry     99      US
1    aryan     95   India
2   tanish     93   India
3  karteek     85      UK

In [14]:
df.to_csv('pd1.csv',index = False)

In [15]:
df.head(2)

    name  marks country
0  harry     99      US
1  aryan     95   India

In [16]:
df.describe()

           marks
count   4.000000
mean   93.000000
std     5.887841
min    85.000000
25%    91.000000
50%    94.000000
75%    96.000000
max    99.000000

In [17]:
pd.read_csv('pd1.csv')

      name  marks country
0    harry     99      US
1    aryan     95   India
2   tanish     93   India
3  karteek     85      UK

In [18]:
ser = pd.Series(np.random.rand(23))

In [19]:
ser

0     0.244256
1     0.379344
2     0.780003
3     0.686541
4     0.006542
5     0.002318
6     0.566531
7     0.817410
8     0.958293
9     0.058247
10    0.947853
11    0.165523
12    0.498712
13    0.640740
14    0.188252
15    0.333977
16    0.789682
17    0.678111
18    0.137067
19    0.825347
20    0.610182
21    0.709718
22    0.356227
dtype: float64

In [20]:
ser.head()

0    0.244256
1    0.379344
2    0.780003
3    0.686541
4    0.006542
dtype: float64

In [21]:
ser.tail()

18    0.137067
19    0.825347
20    0.610182
21    0.709718
22    0.356227
dtype: float64

In [22]:
type(ser)

pandas.core.series.Series

In [23]:
ser.index()

TypeError: 'RangeIndex' object is not callable

In [24]:
dict.index()

AttributeError: 'dict' object has no attribute 'index'